// Mocks generated by Mockito 5.0.17 from annotations
// in nubanktest/test/data/datasource/shortener.data_source.test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nubanktest/core/http/dio_impl.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [DioImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioImpl extends _i1.Mock implements _i2.DioImpl {
  MockDioImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get(String? endpoint) =>
      (super.noSuchMethod(Invocation.method(#get, [endpoint]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
  @override
  _i3.Future<dynamic> post(String? endpoint, dynamic body) =>
      (super.noSuchMethod(Invocation.method(#post, [endpoint, body]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
